server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://127.0.0.1:3000/loki/api/v1/push

scrape_configs:
  - job_name: combined_log
    static_configs:
      - targets:
          - localhost:80
    labels:
      job: combined_logs
      __path__: /Users/fernandojunior/Desktop/project-social-sommittee/sommittee-back-end/combined.log
